python create_model_train_amazon_reviews.py Automotive###Automotive_Enthusiast_Merchandise_train.txt
python create_model_train_amazon_reviews.py Automotive###Car_Care_train.txt
python create_model_train_amazon_reviews.py Automotive###Exterior_Accessories_train.txt
python create_model_train_amazon_reviews.py Automotive###Interior_Accessories_train.txt
python create_model_train_amazon_reviews.py Automotive###Lights_\&_Lighting_Accessories_train.txt
python create_model_train_amazon_reviews.py Automotive###Motorcycle_\&_Powersports_train.txt
python create_model_train_amazon_reviews.py Automotive###Oils_\&_Fluids_train.txt
python create_model_train_amazon_reviews.py Automotive###Paint,_Body_\&_Trim_train.txt
python create_model_train_amazon_reviews.py Automotive###Performance_Parts_\&_Accessories_train.txt
python create_model_train_amazon_reviews.py Automotive###Replacement_Parts_train.txt
python create_model_train_amazon_reviews.py Automotive###RV_Parts_\&_Accessories_train.txt
python create_model_train_amazon_reviews.py Automotive###Tires_\&_Wheels_train.txt
python create_model_train_amazon_reviews.py Automotive###Tools_\&_Equipment_train.txt
python create_model_train_amazon_reviews.py Automotive_train.txt
python create_model_train_amazon_reviews.py Books###Education_\&_Teaching_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Alternative_Rock_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Blues_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Broadway_\&_Vocalists_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Christian_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Classical_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Classic_Rock_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Comedy_\&_Spoken_Word_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Country_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Dance_\&_Electronic_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Folk_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Gospel_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Holiday_\&_Wedding_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Jazz_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Karaoke_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Latin_Music_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Metal_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###New_Age_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Opera_\&_Classical_Vocal_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Pop_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Rap_\&_Hip-Hop_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###R&B_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Reggae_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Rock_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Soundtracks_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###Special_Interest_train.txt
python create_model_train_amazon_reviews.py CDs_\&_Vinyl###World_Music_train.txt
python create_model_train_amazon_reviews.py Cell_Phones_\&_Accessories###Accessories_train.txt
python create_model_train_amazon_reviews.py Clothing,_Shoes_\&_Jewelry###Boys_train.txt
python create_model_train_amazon_reviews.py Clothing,_Shoes_\&_Jewelry###B_train.txt
python create_model_train_amazon_reviews.py Clothing,_Shoes_\&_Jewelry###Girls_train.txt
python create_model_train_amazon_reviews.py Clothing,_Shoes_\&_Jewelry###Luggage_\&_Travel_Gear_train.txt
python create_model_train_amazon_reviews.py Clothing,_Shoes_\&_Jewelry###Men_train.txt
python create_model_train_amazon_reviews.py Clothing,_Shoes_\&_Jewelry###Novelty,_Costumes_\&_More_train.txt
python create_model_train_amazon_reviews.py Clothing,_Shoes_\&_Jewelry###O_train.txt
python create_model_train_amazon_reviews.py Clothing,_Shoes_\&_Jewelry###Women_train.txt
python create_model_train_amazon_reviews.py Digital_Music###Alternative_Rock_train.txt
python create_model_train_amazon_reviews.py Digital_Music###Country_train.txt
python create_model_train_amazon_reviews.py Digital_Music###Hard_Rock_\&_Metal_train.txt
python create_model_train_amazon_reviews.py Digital_Music###Jazz_train.txt
python create_model_train_amazon_reviews.py Digital_Music###Pop_train.txt
python create_model_train_amazon_reviews.py Digital_Music###Rap_\&_Hip-Hop_train.txt
python create_model_train_amazon_reviews.py Electronics###Accessories_\&_Supplies_train.txt
python create_model_train_amazon_reviews.py Electronics###Camera_\&_Photo_train.txt
python create_model_train_amazon_reviews.py Electronics###Car_\&_Vehicle_Electronics_train.txt
python create_model_train_amazon_reviews.py Electronics###Computers_\&_Accessories_train.txt
python create_model_train_amazon_reviews.py Electronics###eBook_Readers_\&_Accessories_train.txt
python create_model_train_amazon_reviews.py Electronics###Portable_Audio_\&_Video_train.txt
python create_model_train_amazon_reviews.py Electronics###Television_\&_Video_train.txt
python create_model_train_amazon_reviews.py Health_\&_Personal_Care###Health_Care_train.txt
python create_model_train_amazon_reviews.py Health_\&_Personal_Care###Household_Supplies_train.txt
python create_model_train_amazon_reviews.py Health_\&_Personal_Care###Medical_Supplies_\&_Equipment_train.txt
python create_model_train_amazon_reviews.py Health_\&_Personal_Care###Stationery_\&_Party_Supplies_train.txt
python create_model_train_amazon_reviews.py Home_\&_Kitchen###Bath_train.txt
python create_model_train_amazon_reviews.py Home_\&_Kitchen###Heating,_Cooling_\&_Air_Quality_train.txt
python create_model_train_amazon_reviews.py Home_\&_Kitchen###Kitchen_\&_Dining_train.txt
python create_model_train_amazon_reviews.py Industrial_\&_Scientific###Janitorial_\&_Sanitation_Supplies_train.txt
python create_model_train_amazon_reviews.py Industrial_\&_Scientific###Material_Handling_Products_train.txt
python create_model_train_amazon_reviews.py Industrial_\&_Scientific###Tapes,_Adhesives_\&_Sealants_train.txt
python create_model_train_amazon_reviews.py Kindle_Store###Kindle_eBooks_train.txt
python create_model_train_amazon_reviews.py Movies_\&_TV###Movies_train.txt
python create_model_train_amazon_reviews.py Movies_\&_TV###TV_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Amplifiers_\&_Effects_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Band_\&_Orchestra_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Bass_Guitars_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###DJ,_Electronic_Music_\&_Karaoke_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Drums_\&_Percussion_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Guitars_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Instrument_Accessories_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Keyboards_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Live_Sound_\&_Stage_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Microphones_\&_Accessories_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Stringed_Instruments_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Studio_Recording_Equipment_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments_train.txt
python create_model_train_amazon_reviews.py Musical_Instruments###Wind_\&_Woodwind_Instruments_train.txt
python create_model_train_amazon_reviews.py Patio,_Lawn_\&_Garden###12-Month_Financing_train.txt
python create_model_train_amazon_reviews.py Patio,_Lawn_\&_Garden###Gardening_\&_Lawn_Care_train.txt
python create_model_train_amazon_reviews.py Patio,_Lawn_\&_Garden###Generators_\&_Portable_Power_train.txt
python create_model_train_amazon_reviews.py Patio,_Lawn_\&_Garden###Lawn_Mowers_\&_Outdoor_Power_Tools_train.txt
python create_model_train_amazon_reviews.py Patio,_Lawn_\&_Garden###Picnic_Baskets_\&_Accessories_train.txt
python create_model_train_amazon_reviews.py Patio,_Lawn_\&_Garden###Snow_Removal_train.txt
python create_model_train_amazon_reviews.py Software###Accounting_\&_Finance_train.txt
python create_model_train_amazon_reviews.py Software###Business_\&_Office_train.txt
python create_model_train_amazon_reviews.py Software###Design_\&_Illustration_train.txt
python create_model_train_amazon_reviews.py Software###Education_\&_Reference_train.txt
python create_model_train_amazon_reviews.py Software###Lifestyle_\&_Hobbies_train.txt
python create_model_train_amazon_reviews.py Software###Music_train.txt
python create_model_train_amazon_reviews.py Software###Photography_train.txt
python create_model_train_amazon_reviews.py Software###Programming_\&_Web_Development_train.txt
python create_model_train_amazon_reviews.py Software###Utilities_train.txt
python create_model_train_amazon_reviews.py Software###Video_train.txt
python create_model_train_amazon_reviews.py Sports_\&_Outdoors###Accessories_train.txt
python create_model_train_amazon_reviews.py Sports_\&_Outdoors###Action_Sports_train.txt
python create_model_train_amazon_reviews.py Sports_\&_Outdoors###Boating_\&_Water_Sports_train.txt
python create_model_train_amazon_reviews.py Sports_\&_Outdoors###Clothing_train.txt
python create_model_train_amazon_reviews.py Sports_\&_Outdoors###Cycling_train.txt
python create_model_train_amazon_reviews.py Sports_\&_Outdoors###Equestrian_Sports_train.txt
python create_model_train_amazon_reviews.py Sports_\&_Outdoors###Fan_Shop_train.txt
python create_model_train_amazon_reviews.py Sports_\&_Outdoors###Outdoor_Gear_train.txt
python create_model_train_amazon_reviews.py Sports_\&_Outdoors###Paintball_\&_Airsoft_train.txt
python create_model_train_amazon_reviews.py Sports_\&_Outdoors###Snow_Sports_train.txt
python create_model_train_amazon_reviews.py Tools_\&_Home_Improvement###Electrical_train.txt
python create_model_train_amazon_reviews.py Tools_\&_Home_Improvement###Hardware_train.txt
python create_model_train_amazon_reviews.py Tools_\&_Home_Improvement###Kitchen_\&_Bath_Fixtures_train.txt
python create_model_train_amazon_reviews.py Tools_\&_Home_Improvement###Lighting_\&_Ceiling_Fans_train.txt
python create_model_train_amazon_reviews.py Tools_\&_Home_Improvement###Painting_Supplies_\&_Wall_Treatments_train.txt
python create_model_train_amazon_reviews.py Tools_\&_Home_Improvement###Power_\&_Hand_Tools_train.txt
python create_model_train_amazon_reviews.py Toys_\&_Games###Tricycles,_Scooters_\&_Wagons_train.txt
python create_model_train_amazon_reviews.py Video_Games###More_Systems_train.txt
python create_model_train_amazon_reviews.py Video_Games###PC_train.txt
