python file_splitter.py Automotive###Automotive_Enthusiast_Merchandise
python file_splitter.py Automotive###Car_Care
python file_splitter.py Automotive###Exterior_Accessories
python file_splitter.py Automotive###Interior_Accessories
python file_splitter.py Automotive###Lights_\&_Lighting_Accessories
python file_splitter.py Automotive###Motorcycle_\&_Powersports
python file_splitter.py Automotive###Oils_\&_Fluids
python file_splitter.py Automotive###Paint,_Body_\&_Trim
python file_splitter.py Automotive###Performance_Parts_\&_Accessories
python file_splitter.py Automotive###Replacement_Parts
python file_splitter.py Automotive###RV_Parts_\&_Accessories
python file_splitter.py Automotive###Tires_\&_Wheels
python file_splitter.py Automotive###Tools_\&_Equipment
python file_splitter.py Automotive
python file_splitter.py Books###Education_\&_Teaching
python file_splitter.py CDs_\&_Vinyl###Alternative_Rock
python file_splitter.py CDs_\&_Vinyl###Blues
python file_splitter.py CDs_\&_Vinyl###Broadway_\&_Vocalists
python file_splitter.py CDs_\&_Vinyl###Christian
python file_splitter.py CDs_\&_Vinyl###Classical
python file_splitter.py CDs_\&_Vinyl###Classic_Rock
python file_splitter.py CDs_\&_Vinyl###Comedy_\&_Spoken_Word
python file_splitter.py CDs_\&_Vinyl###Country
python file_splitter.py CDs_\&_Vinyl###Dance_\&_Electronic
python file_splitter.py CDs_\&_Vinyl###Folk
python file_splitter.py CDs_\&_Vinyl###Gospel
python file_splitter.py CDs_\&_Vinyl###Holiday_\&_Wedding
python file_splitter.py CDs_\&_Vinyl###Jazz
python file_splitter.py CDs_\&_Vinyl###Karaoke
python file_splitter.py CDs_\&_Vinyl###Latin_Music
python file_splitter.py CDs_\&_Vinyl###Metal
python file_splitter.py CDs_\&_Vinyl###New_Age
python file_splitter.py CDs_\&_Vinyl###Opera_\&_Classical_Vocal
python file_splitter.py CDs_\&_Vinyl###Pop
python file_splitter.py CDs_\&_Vinyl###Rap_\&_Hip-Hop
python file_splitter.py CDs_\&_Vinyl###R&B
python file_splitter.py CDs_\&_Vinyl###Reggae
python file_splitter.py CDs_\&_Vinyl###Rock
python file_splitter.py CDs_\&_Vinyl###Soundtracks
python file_splitter.py CDs_\&_Vinyl###Special_Interest
python file_splitter.py CDs_\&_Vinyl###World_Music
python file_splitter.py Cell_Phones_\&_Accessories###Accessories
python file_splitter.py Clothing,_Shoes_\&_Jewelry###Boys
python file_splitter.py Clothing,_Shoes_\&_Jewelry###B
python file_splitter.py Clothing,_Shoes_\&_Jewelry###Girls
python file_splitter.py Clothing,_Shoes_\&_Jewelry###Luggage_\&_Travel_Gear
python file_splitter.py Clothing,_Shoes_\&_Jewelry###Men
python file_splitter.py Clothing,_Shoes_\&_Jewelry###Novelty,_Costumes_\&_More
python file_splitter.py Clothing,_Shoes_\&_Jewelry###O
python file_splitter.py Clothing,_Shoes_\&_Jewelry###Women
python file_splitter.py Digital_Music###Alternative_Rock
python file_splitter.py Digital_Music###Country
python file_splitter.py Digital_Music###Hard_Rock_\&_Metal
python file_splitter.py Digital_Music###Jazz
python file_splitter.py Digital_Music###Pop
python file_splitter.py Digital_Music###Rap_\&_Hip-Hop
python file_splitter.py Electronics###Accessories_\&_Supplies
python file_splitter.py Electronics###Camera_\&_Photo
python file_splitter.py Electronics###Car_\&_Vehicle_Electronics
python file_splitter.py Electronics###Computers_\&_Accessories
python file_splitter.py Electronics###eBook_Readers_\&_Accessories
python file_splitter.py Electronics###Portable_Audio_\&_Video
python file_splitter.py Electronics###Television_\&_Video
python file_splitter.py Health_\&_Personal_Care###Health_Care
python file_splitter.py Health_\&_Personal_Care###Household_Supplies
python file_splitter.py Health_\&_Personal_Care###Medical_Supplies_\&_Equipment
python file_splitter.py Health_\&_Personal_Care###Stationery_\&_Party_Supplies
python file_splitter.py Home_\&_Kitchen###Bath
python file_splitter.py Home_\&_Kitchen###Heating,_Cooling_\&_Air_Quality
python file_splitter.py Home_\&_Kitchen###Kitchen_\&_Dining
python file_splitter.py Industrial_\&_Scientific###Janitorial_\&_Sanitation_Supplies
python file_splitter.py Industrial_\&_Scientific###Material_Handling_Products
python file_splitter.py Industrial_\&_Scientific###Tapes,_Adhesives_\&_Sealants
python file_splitter.py Kindle_Store###Kindle_eBooks
python file_splitter.py Movies_\&_TV###Movies
python file_splitter.py Movies_\&_TV###TV
python file_splitter.py Musical_Instruments###Amplifiers_\&_Effects
python file_splitter.py Musical_Instruments###Band_\&_Orchestra
python file_splitter.py Musical_Instruments###Bass_Guitars
python file_splitter.py Musical_Instruments###DJ,_Electronic_Music_\&_Karaoke
python file_splitter.py Musical_Instruments###Drums_\&_Percussion
python file_splitter.py Musical_Instruments###Guitars
python file_splitter.py Musical_Instruments###Instrument_Accessories
python file_splitter.py Musical_Instruments###Keyboards
python file_splitter.py Musical_Instruments###Live_Sound_\&_Stage
python file_splitter.py Musical_Instruments###Microphones_\&_Accessories
python file_splitter.py Musical_Instruments###Stringed_Instruments
python file_splitter.py Musical_Instruments###Studio_Recording_Equipment
python file_splitter.py Musical_Instruments
python file_splitter.py Musical_Instruments###Wind_\&_Woodwind_Instruments
python file_splitter.py Patio,_Lawn_\&_Garden###12-Month_Financing
python file_splitter.py Patio,_Lawn_\&_Garden###Gardening_\&_Lawn_Care
python file_splitter.py Patio,_Lawn_\&_Garden###Generators_\&_Portable_Power
python file_splitter.py Patio,_Lawn_\&_Garden###Lawn_Mowers_\&_Outdoor_Power_Tools
python file_splitter.py Patio,_Lawn_\&_Garden###Picnic_Baskets_\&_Accessories
python file_splitter.py Patio,_Lawn_\&_Garden###Snow_Removal
python file_splitter.py Software###Accounting_\&_Finance
python file_splitter.py Software###Business_\&_Office
python file_splitter.py Software###Design_\&_Illustration
python file_splitter.py Software###Education_\&_Reference
python file_splitter.py Software###Lifestyle_\&_Hobbies
python file_splitter.py Software###Music
python file_splitter.py Software###Photography
python file_splitter.py Software###Programming_\&_Web_Development
python file_splitter.py Software###Utilities
python file_splitter.py Software###Video
python file_splitter.py Sports_\&_Outdoors###Accessories
python file_splitter.py Sports_\&_Outdoors###Action_Sports
python file_splitter.py Sports_\&_Outdoors###Boating_\&_Water_Sports
python file_splitter.py Sports_\&_Outdoors###Clothing
python file_splitter.py Sports_\&_Outdoors###Cycling
python file_splitter.py Sports_\&_Outdoors###Equestrian_Sports
python file_splitter.py Sports_\&_Outdoors###Fan_Shop
python file_splitter.py Sports_\&_Outdoors###Outdoor_Gear
python file_splitter.py Sports_\&_Outdoors###Paintball_\&_Airsoft
python file_splitter.py Sports_\&_Outdoors###Snow_Sports
python file_splitter.py Tools_\&_Home_Improvement###Electrical
python file_splitter.py Tools_\&_Home_Improvement###Hardware
python file_splitter.py Tools_\&_Home_Improvement###Kitchen_\&_Bath_Fixtures
python file_splitter.py Tools_\&_Home_Improvement###Lighting_\&_Ceiling_Fans
python file_splitter.py Tools_\&_Home_Improvement###Painting_Supplies_\&_Wall_Treatments
python file_splitter.py Tools_\&_Home_Improvement###Power_\&_Hand_Tools
python file_splitter.py Toys_\&_Games###Tricycles,_Scooters_\&_Wagons
python file_splitter.py Video_Games###More_Systems
python file_splitter.py Video_Games###PC
