python merge_data.py d_meta_Sports_and_Outdoors reviews_Sports_and_Outdoors meta_reviews_Sports_and_Outdoors
python merge_data.py d_meta_Automotive reviews_Automotive meta_reviews_Automotive
python merge_data.py d_meta_Musical_Instruments reviews_Musical_Instruments meta_reviews_Musical_Instruments
python merge_data.py d_meta_Video_Games reviews_Video_Games meta_reviews_Video_Games